### ISSUE TITLE
Autocomplete is incomplete

### ISSUE THREAD

**Issue by mrakgr** [leanprover/vscode-lean#130]
```
import data.rat
import data.vector

def E {n} (l : vector rat n) : rat := list.foldl (+) 0 l.val / n
```

I can't get `foldl` to show up in autocomplete. That same goes for `val`. `data.vector` and `data.rat` are from the `mathlib`. I am using VS Code with Windows 10. Lean version 3.42.

Reposted from [here](https://github.com/leanprover/lean/issues/2001).

**Comment by bryangingechen** [comment]
It's true that Lean's autocomplete can be unreliable. Unfortunately, there's not that much that can be done from the VS Code extension side of things, since it relies entirely on the completions returned from the Lean server. Sorry for redirecting you again, but the best place for this issue might be the [`leanprover-community/lean` issues](https://github.com/leanprover-community/lean/issues) since that fork is (slightly) more active than the official Lean 3 project.

For what it's worth (Lean 3.4.2, VS Code on macOS 10.14), I do see `foldl` when I place the cursor on it and hit the keyboard shortcut for "Trigger Suggestion" (`Ctrl+Space` by default):

<img width="559" alt="Screenshot 2019-10-14 09 57 05" src="https://user-images.githubusercontent.com/5209952/66757118-709fac00-ee69-11e9-9556-affefc093855.png">

I don't see `val` in the suggestions at the other position though:

<img width="807" alt="Screenshot 2019-10-14 09 57 28" src="https://user-images.githubusercontent.com/5209952/66757175-8e6d1100-ee69-11e9-8385-9e0f59304db1.png">

**Comment by digama0** [comment]
You sometimes have to try it multiple times, but `list.foldl` should come up if it is imported, as in @bryangingechen 's example.

The example with `subtype.val` is harder because projections are not resolved until later. There is probably a better way to handle this but it would require some structural modifications to the parser, because there is an ambiguity between namespaced names and projections. Basically, lean knows at the time that you search that it is `*.val`, but it doesn't know what `*` is until typechecking is done.

**Comment by mrakgr** [comment]
I see. Well, I'll let you guys decide what to do with this issue. I'll close the other one.

**Comment by digama0** [comment]
If a fix is going to happen, it needs to happen on the `lean` project. I wouldn't hold my breath for it though, unless you are interested in diving into the code yourself.

**Comment by mrakgr** [comment]
In that case I'd probably be better off seeing whether this gets fixed in Lean 4 then. Very well.

Thank you for the info.
