### ISSUE TITLE
precedence of translations.json entries

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/vscode-lean#199]
I made a mistake in #196 , and duplicated the key for `\^c`.
The issue was that `\^c` already existed (line ~1137) but `\^chi` is declared at line ~1237 and apparently takes precedence when typing `\^c`.

Do you know what is going on here? Why is `\^chi` taking precedence over `\^c`, but not (e.g.) `\aeeqfun` taking precedence over `\a` (so it's not just "the later it is declared the more precedence it has")? 
Could we change the setting so it always chooses a minimal match (i.e. don't find a match if there is a prefix that also matches), or at least that always respects exact matches?

Or can I sort `translations.json` in such a way that this happens without setting changes? How should I sort it to obtain this behavior?

**Comment by gebner** [comment]
The order in the file should not matter.  The current rules are as follows:
 1. If there's an exact match, return that.
 2. Otherwise look for the shortest abbreviation that extends the current input.

BTW, I'm not sure if I get the same results as you:
 - `\^c` is converted to `ᶜ`
 - `\^ch` is converted to `ᵡ`
 - `\^chi` is converted to `ᵡ`
 - `\a` is converted to `α`
 - `\ae` is converted to `æ`
 - `\aee` is converted to `→ₘ`
 - `\aeeqfun` is converted to `→ₘ`

**Comment by fpvandoorn** [comment]
Ah, I see what's going on. I'm using the released version from May 26, and the commit that adds the missing unicode characters was from June 16.
