### ISSUE TITLE
confusing response to check open files

### ISSUE THREAD

**Issue by cartazio** [leanprover/vscode-lean#49]
![screen shot 2017-06-10 at 11 39 46 am](https://user-images.githubusercontent.com/4290/27004103-920d837a-4dd1-11e7-914d-3b3f008b9f72.png)

maybe i'm missing something obvious, though its definetly true that the the highlighting ux for errors is pretty nice

**Comment by johoelzl** [comment]
Thanks for the error report.

The Error messages should appear because the command is known to VS Code, but not active as the Lean plugin only gets activated when a Lean file is opened.

In the latest VS Code version is a way to only show commands under certain conditions using the special "commandpalette" menu. I will work on it.
