### ISSUE TITLE
Certain Keywords Not Highlighted

### ISSUE THREAD

**Issue by OwenGraves** [leanprover/vscode-lean#60]
The keywords "proposition" and "corollary" (synonyms of theorem) are not highlighted (probably several others, but these are the ones I've noticed). If anyone else notices other missing keywords perhaps post them here?

My guess for a fix would be to add them to this list on line 29 of syntaxes/lean.json?
`"begin": "\\b(inductive|coinductive|structure|theorem|axiom|axioms|lemma|...`

**Comment by gebner** [comment]
> The keywords "proposition" and "corollary" (synonyms of theorem) are not highlighted (probably several others, but these are the ones I've noticed). If anyone else notices other missing keywords perhaps post them here?

These are [no longer keywords in the current version of lean](https://github.com/leanprover/lean/issues/1432), so we removed the highlighting for them.  At the moment, `proposition` and `corollary` are valid identifiers.

I know this situation is not ideal since the highlighting is off for older Lean versions, but we have to pick a version for the syntax highlighting.  Since most users are using the latest release (or even the unstable git version), we focus on that.
