### ISSUE TITLE
autocomplete doesn't have keywords

### ISSUE THREAD

**Issue by diakopter** [leanprover/vscode-lean#8]

**Comment by Kha** [comment]
I'm not sure if it makes sense to just intermix keywords with the regular completion items. I would very much like to provide completion for "command" keywords (`def`, `instance`, ...), but the problem is that the Lean grammar can be ambiguous as to whether the next token should be a command keyword. For example, in

```lean
def f := x

de
```
we do not know whether to complete `de` to a command, or an expression that will be applied to `x`.

BTW, since the completion selection is done purely server-side, this issue should probable be moved to leanprover/lean.

**Comment by jroesch** [comment]
We can implement a relatively reliable version that does command completion in the editor, other languages do this. We can look into how TypeScript, Go, etc does it.
